"""upgrade memories table with vector embeddings and metadata

Revision ID: 2edc5bf40f65
Revises: 7580c1c40250
Create Date: 2026-09-06 10:52:03.671697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '2edc5bf40f65'
down_revision: Union[str, Sequence[str], None] = '7580c1c40250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE memorytype ADD VALUE IF NOT EXISTS 'decision';")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('memories', sa.Column('importance', sa.String(length=20), nullable=True))
    op.add_column('memories', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('memories', sa.Column('source_session_id', sa.String(length=36), nullable=True))
    op.add_column('memories', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_foreign_key(None, 'memories', 'sessions', ['source_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'embedding')
    op.drop_column('memories', 'source_session_id')
    op.drop_column('memories', 'confidence')
    op.drop_column('memories', 'importance')
    op.drop_column('memories', 'subject')
    # ### end Alembic commands ###
